import { Page } from "../@libs/widgets";
import { TagsSection } from "./@components/tags-section";

export default () =>
  Page({
    title: "Batua | Tags & Categories",
    headerTitle: "Categorise your transactions using tags",
    selectedTabIndex: 3,
    mainContent: [
      TagsSection({
        title: "Fixed tags generated by system",
        categories: ["NECESSITY", "PAYMENT_SOURCE", "PAYMENT_METHOD"],
      }),
      TagsSection({
        title: "Editable tags added by you and pre-existing ones",
        categories: ["COMMUTE", "TRAVEL", "SHOP_OR_MARKET", "PRODUCT_CATEGORY"],
      }),
    ],
    sideContent: "",
  });
