export const CURRENCIES = [
  { code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
  { code: "ALL", name: "Albania Lek", symbol: "Lek" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏" },
  { code: "ANG", name: "Netherlands Antilles Guilder", symbol: "ƒ" },
  { code: "ARS", name: "Argentina Peso", symbol: "$" },
  { code: "AUD", name: "Australia Dollar", symbol: "AU$" },
  { code: "AWG", name: "Aruba Florin", symbol: "ƒ" },
  { code: "AZN", name: "Azerbaijan Manat", symbol: "₼" },
  { code: "BAM", name: "Convertible Mark", symbol: "KM" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "BGN", name: "Bulgaria Lev", symbol: "лв" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "د.ب." },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "BMD", name: "Bermuda Dollar", symbol: "BD$" },
  { code: "BND", name: "Brunei Darussalam Dollar", symbol: "B$" },
  { code: "BOB", name: "Bolivia Bolíviano", symbol: "$b" },
  { code: "BRL", name: "Brazil Real", symbol: "R$" },
  { code: "BSD", name: "Bahamas Dollar", symbol: "B$" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu" },
  { code: "BWP", name: "Botswana Pula", symbol: "P" },
  { code: "BYN", name: "Belarus Ruble", symbol: "Br" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
  { code: "CLP", name: "Chile Peso", symbol: "CLP$" },
  { code: "CLF", name: "Chilean Unit of Account (UF)", symbol: "CLF" },
  { code: "CNY", name: "China Yuan Renminbi", symbol: "¥" },
  { code: "COP", name: "Colombia Peso", symbol: "COL$" },
  { code: "CRC", name: "Costa Rica Colon", symbol: "₡" },
  { code: "CUP", name: "Cuba Peso", symbol: "₱" },
  { code: "CVE", name: "Cape Verdean escudo", symbol: "CVE" },
  { code: "CYP", name: "Cypriot Pound", symbol: "£" },
  { code: "CZK", name: "Czech Republic Koruna", symbol: "Kč" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "DKK", name: "Denmark Krone", symbol: "kr" },
  { code: "DOP", name: "Dominican Republic Peso", symbol: "RD$" },
  { code: "DZD", name: "Algerian Dinar", symbol: "دج" },
  { code: "EEK", name: "Estonian Kroon", symbol: "kr" },
  { code: "EGP", name: "Egypt Pound", symbol: "£" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nkf" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "ብር" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "FIM", name: "Finnish Markka", symbol: "MK" },
  { code: "FJD", name: "Fiji Dollar", symbol: "FJ$" },
  { code: "FKP", name: "Malvinas Pound", symbol: "£" },
  { code: "Fr", name: "Franc", symbol: "Fr" },
  { code: "GBP", name: "United Kingdom Pound", symbol: "£" },
  { code: "GEL", name: "Georgian Lari", symbol: "ლ" },
  { code: "GGP", name: "Guernsey Pound", symbol: "£" },
  { code: "GHS", name: "Ghana Cedi", symbol: "¢" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { code: "GNF", name: "Guinean franc", symbol: "GFr" },
  { code: "GTQ", name: "Guatemala Quetzal", symbol: "Q" },
  { code: "GYD", name: "Guyana Dollar", symbol: "GY$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "HNL", name: "Honduras Lempira", symbol: "L" },
  { code: "HRK", name: "Croatia Kuna", symbol: "kn" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G" },
  { code: "HUF", name: "Hungary Forint", symbol: "Ft" },
  { code: "IDR", name: "Indonesia Rupiah", symbol: "Rp" },
  { code: "IEP", name: "Irish Pound", symbol: "IR£" },
  { code: "ILS", name: "Israel Shekel", symbol: "₪" },
  { code: "IMP", name: "Isle of Man Pound", symbol: "£" },
  { code: "INR", name: "India Rupee", symbol: "₹" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
  { code: "IRR", name: "Iran Rial", symbol: "﷼" },
  { code: "ISK", name: "Iceland Krona", symbol: "KR" },
  { code: "JEP", name: "Jersey Pound", symbol: "£" },
  { code: "JMD", name: "Jamaica Dollar", symbol: "J$" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
  { code: "JPY", name: "Japan Yen", symbol: "¥" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "KGS", name: "Kyrgyzstan Som", symbol: "лв" },
  { code: "KHR", name: "Cambodia Riel", symbol: "៛" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF" },
  { code: "KPW", name: "North Korean Won", symbol: "₩" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$" },
  { code: "KZ", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "KZT", name: "Kazakhstan Tenge", symbol: "лв" },
  { code: "LAK", name: "Laos Kip", symbol: "₭" },
  { code: "LBP", name: "Lebanon Pound", symbol: "£" },
  { code: "LSL", name: "Lesotho Loti", symbol: "LSL" },
  { code: "LKR", name: "Sri Lanka Rupee", symbol: "₨" },
  { code: "LRD", name: "Liberia Dollar", symbol: "L$" },
  { code: "LTL", name: "Lithuanian Litas", symbol: "Lt" },
  { code: "LUF", name: "Luxembourg Franc", symbol: "F" },
  { code: "LVL", name: "Latvian Lats", symbol: "Ls" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "MDN", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "MGF", name: "Madagascar Franc", symbol: "MF" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
  { code: "MMK", name: "Burmese Kyat", symbol: "K" },
  { code: "MNT", name: "Mongolian Tögrög", symbol: "₮" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$" },
  { code: "MRU", name: "Mauritanian ouguiya", symbol: "UM" },
  { code: "MTL", name: "Maltese Lira", symbol: "Lm" },
  { code: "MUR", name: "Mauritius Rupee", symbol: "₨" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf" },
  { code: "MWK", name: "Malawian kwacha", symbol: "K" },
  { code: "MXN", name: "Mexico Peso", symbol: "Mex$" },
  { code: "MYR", name: "Malaysia Ringgit", symbol: "RM" },
  { code: "MZN", name: "Mozambique Metical", symbol: "MT" },
  { code: "NAD", name: "Namibia Dollar", symbol: "N$" },
  { code: "NGN", name: "Nigeria Naira", symbol: "₦" },
  { code: "NIO", name: "Nicaragua Cordoba", symbol: "C$" },
  { code: "NOK", name: "Norway Krone", symbol: "kr" },
  { code: "NPR", name: "Nepal Rupee", symbol: "₨" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "OMR", name: "Oman Rial", symbol: "﷼" },
  { code: "PAB", name: "Panama Balboa", symbol: "B/." },
  { code: "PEN", name: "Peru Sol", symbol: "S/." },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
  { code: "PHP", name: "Philippines Peso", symbol: "₱" },
  { code: "PKR", name: "Pakistan Rupee", symbol: "₨" },
  { code: "PLN", name: "Poland Zloty", symbol: "zł" },
  { code: "PYG", name: "Paraguay Guarani", symbol: "Gs" },
  { code: "QAR", name: "Qatar Riyal", symbol: "﷼" },
  { code: "RON", name: "Romania Leu", symbol: "lei" },
  { code: "RSD", name: "Serbia Dinar", symbol: "Дин." },
  { code: "RUB", name: "Russia Ruble", symbol: "₽" },
  { code: "RWF", name: "Rwandan Franc", symbol: "R₣" },
  { code: "SAR", name: "Saudi Arabia Riyal", symbol: "﷼" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "Si$" },
  { code: "SCR", name: "Seychelles Rupee", symbol: "₨" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
  { code: "SEK", name: "Sweden Krona", symbol: "kr" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£" },
  { code: "SKK", name: "Slovak Koruna", symbol: "Sk" },
  { code: "SLL", name: "Sierra Leonean leone", symbol: "Le" },
  { code: "SOS", name: "Somalia Shilling", symbol: "S" },
  { code: "SRD", name: "Suriname Dollar", symbol: "Sr$" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SS£" },
  { code: "STD", name: "São Tomé & Príncipe Dobra", symbol: "Db" },
  { code: "SVC", name: "El Salvador Colon", symbol: "₡" },
  { code: "SYP", name: "Syria Pound", symbol: "£" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L" },
  { code: "THB", name: "Thailand Baht", symbol: "฿" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM" },
  { code: "TMT", name: "Turkmenistan Manat", symbol: "T" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "TRY", name: "Turkey Lira", symbol: "₺" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "TT$" },
  { code: "TVD", name: "Tuvalu Dollar", symbol: "TV$" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
  { code: "TZS", name: "Tanzanian shilling", symbol: "TSh" },
  { code: "UAH", name: "Ukraine Hryvnia", symbol: "₴" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "USD", name: "United States Dollar", symbol: "$" },
  { code: "UYU", name: "Uruguay Peso", symbol: "$U" },
  { code: "UZS", name: "Uzbekistan Som", symbol: "лв" },
  { code: "VES", name: "Venezuela Bolívar", symbol: "Bs" },
  { code: "VND", name: "Vietnam Dong", symbol: "₫" },
  { code: "WST", name: "Samoan Tālā", symbol: "WS$" },
  { code: "XAF", name: "Central African CFA franc", symbol: "FCFA" },
  { code: "XCD", name: "Eastern Caribbean Dollar", symbol: "EC$" },
  { code: "XOF", name: "West African CFA franc", symbol: "CFA" },
  { code: "XPF", name: "Central Pacific franc", symbol: "F" },
  { code: "YER", name: "Yemen Rial", symbol: "﷼" },
  { code: "ZAR", name: "South Africa Rand", symbol: "R" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "K" },
  { code: "ZWD", name: "Zimbabwe Dollar", symbol: "Z$" },
] as const;

export type Currency = (typeof CURRENCIES)[number];
export type CurrencyCode = Currency["code"];
