import { Account, PaymentMethod, Tag } from "../models";

type MockData = {
  ACCOUNTS: Account[];
  PAYMENT_METHODS: PaymentMethod[];
  TAGS: Tag[];
};

export const MOCK: MockData = {
  ACCOUNTS: [
    {
      id: "CASH",
      name: "Cash in Wallet",
      balance: 3587,
      currency: "INR",
    },
    {
      id: "ICICI_SAVINGS",
      accountId: "022901511014",
      name: "ICICI Savings Account",
      balance: 118495,
      currency: "INR",
    },
    {
      id: "HDFC_SAVINGS",
      accountId: "3600012345689",
      name: "HDFC Savings Account",
      balance: 835723,
      currency: "INR",
    },
    {
      id: "AXIS_SAVINGS",
      accountId: "549912345689",
      name: "Axis Savings Account",
      balance: 9423,
      currency: "INR",
    },
    {
      id: "AXIS_CREDIT",
      accountId: "549922228888",
      name: "Axis Credit Account",
      balance: 90000,
      currency: "INR",
    },
    {
      id: "SODEXO",
      accountId: "chnkrydv@sodexo.com",
      name: "Sodexo",
      balance: 2200,
      currency: "INR",
    },
  ],
  PAYMENT_METHODS: [
    {
      code: "COINS_NOTES",
      displayName: "Coins & Notes",
      defaultAccountId: "CASH",
      connectedAccountIds: ["CASH"],
    },
    {
      code: "GPAY",
      displayName: "Google Pay",
      uniqueId: "9852430671@okaxis",
      defaultAccountId: "ICICI_SAVINGS",
      connectedAccountIds: ["ICICI_SAVINGS"],
    },
    {
      code: "PHONEPE",
      displayName: "PhonePe",
      uniqueId: "9852430671@ybl",
      defaultAccountId: "ICICI_SAVINGS",
      connectedAccountIds: ["ICICI_SAVINGS"],
    },
    {
      code: "PAYTM",
      displayName: "Paytm",
      uniqueId: "9852430671@paytm",
      defaultAccountId: "ICICI_SAVINGS",
      connectedAccountIds: ["ICICI_SAVINGS", "AXIS_SAVINGS"],
    },
    {
      code: "ICICI_DEBIT",
      displayName: "ICICI Debit Card",
      uniqueId: "4300111122223333",
      expiry: new Date(2028, 10),
      defaultAccountId: "ICICI_SAVINGS",
      connectedAccountIds: ["ICICI_SAVINGS"],
    },
    {
      code: "AXIS_CREDIT",
      displayName: "AXIS Credit Card",
      uniqueId: "4300111122223333",
      expiry: new Date(2026, 3),
      defaultAccountId: "AXIS_CREDIT",
      connectedAccountIds: ["AXIS_CREDIT"],
    },
    {
      code: "ICICI_NET_BANKING",
      displayName: "ICICI Net Banking",
      defaultAccountId: "ICICI_SAVINGS",
      connectedAccountIds: ["ICICI_SAVINGS"],
    },
    {
      code: "HDFC_NET_BANKING",
      displayName: "HDFC Net Banking",
      defaultAccountId: "HDFC_SAVINGS",
      connectedAccountIds: ["HDFC_SAVINGS"],
    },
    {
      code: "SODEXO_COUPONS",
      displayName: "Sodexo Coupons",
      uniqueId: "chnkrydv@sodexo.com",
      expiry: new Date(2025, 0, 31),
      defaultAccountId: "SODEXO",
      connectedAccountIds: ["SODEXO"],
    },
  ],
  TAGS: [
    {
      id: "0",
      name: "cash",
      type: "PAYMENT_SOURCE",
      isDeletable: false,
    },
    {
      id: "1",
      name: "icicibank",
      type: "PAYMENT_SOURCE",
      isDeletable: false,
    },
    {
      id: "2",
      name: "hdfcbank",
      type: "PAYMENT_SOURCE",
      isDeletable: false,
    },
    {
      id: "3",
      name: "axisbank",
      type: "PAYMENT_SOURCE",
      isDeletable: false,
    },
    {
      id: "4",
      name: "sodexo",
      type: "PAYMENT_SOURCE",
      isDeletable: false,
    },
    {
      id: "5",
      name: "coinsnnotes",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "6",
      name: "gpay",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "7",
      name: "phonepe",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "8",
      name: "paytm",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "9",
      name: "icicidebitcard",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "10",
      name: "axiscreditcard",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "11",
      name: "icicinetbanking",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "12",
      name: "hdfcnetbanking",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "13",
      name: "sodexocoupons",
      type: "PAYMENT_METHOD",
      isDeletable: false,
    },
    {
      id: "14",
      name: "essentials",
      type: "NECESSITY",
      isDeletable: false,
    },
    {
      id: "15",
      name: "maybeluxary",
      type: "NECESSITY",
      isDeletable: false,
    },
    {
      id: "16",
      name: "luxary",
      type: "NECESSITY",
      isDeletable: false,
    },
    {
      id: "17",
      name: "uber",
      type: "COMMUTE",
      isDeletable: true,
    },
    {
      id: "18",
      name: "airbnb",
      type: "TRAVEL",
      isDeletable: true,
    },
    {
      id: "19",
      name: "bookingdotcom",
      type: "TRAVEL",
      isDeletable: true,
    },
    {
      id: "20",
      name: "decathlon",
      type: "SHOP_OR_MARKET",
      isDeletable: true,
    },
    {
      id: "21",
      name: "amazon",
      type: "SHOP_OR_MARKET",
      isDeletable: true,
    },
    {
      id: "22",
      name: "ikea",
      type: "SHOP_OR_MARKET",
      isDeletable: true,
    },
    {
      id: "23",
      name: "grocery",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "24",
      name: "apparel",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "25",
      name: "gadgets",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "26",
      name: "furniture",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "27",
      name: "grooming",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "28",
      name: "gifting",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "29",
      name: "jewellery",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "30",
      name: "stationery",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "31",
      name: "books",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "32",
      name: "gardening",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "33",
      name: "sportsnfitness",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "34",
      name: "treatment",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "35",
      name: "vehicle",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "36",
      name: "outing",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "37",
      name: "softwareapp",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "38",
      name: "appliances",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "39",
      name: "education",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "40",
      name: "petsupplies",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "41",
      name: "diningout",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "42",
      name: "homenkitchen",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "43",
      name: "luggagenbags",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "44",
      name: "toysngames",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "44",
      name: "accessories",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
    {
      id: "45",
      name: "moviesnshows",
      type: "PRODUCT_CATEGORY",
      isDeletable: true,
    },
  ],
};
